Ext.define('DragDrop.config.Configuration', {
	
	statics: {

		LOGO				:	'resources/images/64x64px-stelmm-logo-1.png',//StelmLogo.jpg',
		SMALLER_LOGO			:	'resources/images/Stelmm_Smaller.png',
		TASKBAR_CONTENT_URL 		:	'data/TaskbarContent.json',
		TASKBAR_MAIN_URL		:	'data/TaskbarContent',
		NOTIFICATION_TIME		:	5000,
		DEMO_NOTIFICATION_INTERVAL	:	600000,
		TASKBARCONTENT_INTERVAL		:	2000,
		EDIT_WINDOW 			:	true,
		GROUPTAB_DEFAULT_COLOR		:	'#F5F5F5',
		DEFAULT_WORKSPACE_TITLE		:	'Untitled',
		TAB_COLOR			:	'#474747',
		TAB_FONT_COLOR			:	'#FFFFFF',
		NEW_WORKSPACE_ICON		:	'resources/images/newworkspace.png',
		NEW_SHORTCUTGROUP_ICON		:	'resources/images/newshortcutgroup.png',
		DEFAULT_ICON			:	'resources/images/workspace.png',
		SCROLLDOWN_IMAGE		:	'resources/images/down.png',
		DEFAULT_TAB_ICON		:	'resources/images/tabtitleicon.png',
		ALERTS_ICON	:	'resources/images/alerts-icon.png',
		CHAT_ICON	:	'resources/images/chat-icon-light.png',
		AUDIO_ICON	:	'resources/images/audio-icon.png',
		FEEDBACK_ICON :	'resources/images/feedback-icon.png',
		SERVER_CONNECTED_ICON	: 	'resources/images/serverconnected-icon-green.png',
		SERVER_NOT_CONNECTED_ICON	: 	'http://stelmmst.walkingtree.in/resources/images/server-notconnected-icon.png',
		MORE_ICON	:	'resources/images/more-icon.png',
		APPITEM_WIDTH	:	100,
		ALL_CATEGORIES_ICON	:	'resources/images/categories-icon.png',
		APPSTOOLBAR_MIN_WIDTH : 96,
		APPSTOOLBAR_SERVER_MIN_WIDTH : 130,
		APPSTOOLBAR_MIN_HEIGHT : 90,
		APPSTOOLBAR_CONFIG_WIDTH : 90,
		DEFAULT_SEARCH_CRITERIA : {
			defaultSearchText : '',
			priceFilterActiveItem : 0,
			categoriesFilterActiveItem : 0,
			relevanceSortActiveItem : 0,
			templateChangeActiveItem : 1
		},
		WIDTH_BADGE			:	42,
		WIDTH_NOBADGE		:	24,
		MENUAPPWINDOW_WIDTH		:	810,
		MENUAPPWINDOW_HEIGHT		:	600,
		ITEM_HEIGHT		:	38,
		FILTER_NAME_IMG :	'resources/images/appname-search-icon.png',
		FILTER_CATEGORYTYPE_IMG : 'resources/images/appcategory-search-icon.png',
		FILTER_TAGS_IMG : 'resources/images/tags-search-icon.png',
		ALL_CATEGORIES 	: 	'allcategories',
		PRICE		    : 	'price',
		FEATURED		:	'featuredapps',
		FAVORITES		:	'myfavorites',
		MYFAV_GRPA		:	'myfavgrpa',
		RELEVANCE		:	'relevance',
		POPULARITY		:	'popularity',
		RATING			:	'rating',
		MOREMENU_TOOLBAR_ITEMSCOUNT	:	10,
		MOREMENU_TOOLBAR_ITEMSWIDTH	:	85,
		MOREMENU_VERTICAL_MIN_WIDTH	:	100,
		MOREMENU_TOOLBAR_ITEMSHEIGHT	:	60,
		MOREMENU_TOOLBAR_ACTUAL_ITEMSCOUNT :	10,
		DUPLICATE_ICON : 'resources/images/duplicate.png',
		DELETE_ICON : 'resources/images/delete.png',
		REVIEW_SETTINGS_ICON : 'resources/images/settings.png',
		MIN_APPS_DASHBOARD	:	7,
		MAX_APPS_DASHBOARD	:	7,
		DASHBOARD_ITMES_JSON_URL : 'data/DashboardItems.json',
		DEFAULT_MENUAPP_CONFIG : {
			xtype : 'menuapp',
			scale : 'medium',
			ui : 'stelmmdark',
			iconAlign : 'top',
			cls : 'stelmm-button-cls'
		},
		DEFAULT_ICON_SIZE : '32x32',
		CREATE_TOOLBAR_ICON	: 'resources/images/createtoolbar.png',
		ADD_TO_DASHBOARD_ICON: 'resources/images/addtodashboard.png',
		APP_DEFAULT_WIDTH : 80,
		APP_DEFAULT_HEIGHT : 60,
		OPEN_TEXT : 'Open',
		DEFAULT_APPMENUBAR_APPSCOUNT : 5,
		DEFAULT_BUTTON_CLS_SELECTOR	 : '.stelmm-button-cls',
		EXTENDED_DASHBOARD_UI : 'stelmmdark',
		APPSTOOLBAR_UI : 'stelmm',
		APPSTOOLBAR_MARGIN : 5,
		APPMENUBAR_MARGIN : 5,
		APP_MARGIN : 5,
		BUTTON_TEXT:12,
		SCROLLBAR_ADJUST_VALUE : 2,
		CASCADEDAPP_DEFAULT_WIDTH : 300,
		CASCADEDAPP_DEFAULT_HEIGHT : 200,
		DEFAULT_BLADES : ['securitypriceblade','quickinfoblade','datablade','quoteblade','quoteandsizeblade','quotesizespreadblade','quotedepthandsizeblade','tradeandquoterecapblade','quickchart'],
		DEFAULTVALUE_TOPOPULATE : 'BHP AU Equity',
		BLADE_DATA_URL : 'data/BladeData.json'
	}
});
