/*
 * File: app/model/Author.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.model.Author', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Field'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'first_name'
        },
        {
            name: 'last_name'
        },
        {
            name: 'nickname'
        },
        {
            name: 'email'
        },
        {
            convert: function(v, rec) {
                return rec.get('first_name') + ' ' + rec.get('last_name');
            },
            name: 'full_name'
        },
        {
            convert: function(v, rec) {
                return 'http://www.gravatar.com/avatar/' + rec.get('email');
            },
            name: 'gavtar_url'
        }
    ]
});