/*
 * File: app/model/Article.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AR.model.Article', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    config: {
        fields: [
            {
                mapping: 'id',
                name: 'articleId',
                type: 'int'
            },
            {
                name: 'title'
            },
            {
                name: 'date',
                type: 'date'
            },
            {
                name: 'content'
            },
            {
                name: 'excerpt'
            },
            {
                name: 'status'
            },
            {
                name: 'author'
            }
        ]
    }
});