/*
 * File: app/view/AuthorsGridPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.AuthorsGridPanel', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.authorsgrid',

    requires: [
        'MyApp.view.AuthorsGridPanelViewModel',
        'Ext.grid.View',
        'Ext.grid.column.Column'
    ],

    viewModel: {
        type: 'mygridpanel12'
    },
    publishes: [
        'selection'
    ],
    width: 230,
    collapsible: true,
    title: 'Authors',
    columnLines: false,
    hideHeaders: true,
    store: 'Authors',

    columns: [
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                return '<img src="' + value + '?s=40"></img>';
            },
            width: 50,
            dataIndex: 'gavtar_url'
        },
        {
            xtype: 'gridcolumn',
            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                metaData.style = 'font-size:1.2em;padding-top:20px;color:#495E88;';
                return value;
            },
            dataIndex: 'full_name',
            text: 'Author',
            flex: 1
        }
    ]

});