/*
 * File: app/view/CenterTabPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.CenterTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.centertabpanel',

    requires: [
        'MyApp.view.CenterTabPanelViewModel',
        'MyApp.view.CenterTabPanelViewController',
        'MyApp.view.ArticlesGridPanel',
        'Ext.grid.Panel',
        'Ext.tab.Tab'
    ],

    config: {
        author: null
    },

    controller: 'centertabpanel',
    viewModel: {
        type: 'centertabpanel'
    },
    activeTab: 0,

    items: [
        {
            xtype: 'articlesgrid',
            reference: 'recentarticles',
            bind: {
                title: '{tabtitle}'
            },
            listeners: {
                select: 'onGridpanelSelect'
            }
        }
    ],

    updateAuthor: function(newVal, oldVal) {
        //set the Recent Arcticles tab title for the selected author
        this.getViewModel().setAuthor(newVal);

        //load author posts
        this.lookupReference('recentarticles').setAuthor(newVal);
    }

});