
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext": "../../ext/src",
  "Ext.Msg": "../../ext/src/window/MessageBox.js",
  "Ext.rtl.EventObjectImpl": "../../ext/src/rtl/EventObject.js",
  "PDFSplitter": "../../app",
  "Setu": "../../lib/setu"
});
Ext.ClassManager.addNameAlternateMappings({
  "PDFSplitter.Application": [],
  "PDFSplitter.controller.PdfSplitterController": [],
  "PDFSplitter.model.DocumentCategory": [],
  "PDFSplitter.model.DocumentType": [],
  "PDFSplitter.model.TreeModel": [],
  "PDFSplitter.store.DocumentCategory": [],
  "PDFSplitter.store.DocumentList": [],
  "PDFSplitter.store.DocumentType": [],
  "PDFSplitter.store.TreeStore": [],
  "PDFSplitter.ux.util.PDF.TextLayerBuilder": [],
  "PDFSplitter.view.DocumentCategory": [],
  "PDFSplitter.view.DocumentList": [],
  "PDFSplitter.view.DocumentType": [],
  "PDFSplitter.view.ErrorPanel": [],
  "PDFSplitter.view.Header": [],
  "PDFSplitter.view.MainPage": [],
  "PDFSplitter.view.PagingToolbar": [],
  "PDFSplitter.view.PdfPanel": [],
  "PDFSplitter.view.ReadFile": [],
  "PDFSplitter.view.SearchBar": [],
  "PDFSplitter.view.SplitContainer": [],
  "PDFSplitter.view.SplitDetailsPanel": [],
  "PDFSplitter.view.TabView": [],
  "PDFSplitter.view.TextContainer": [],
  "PDFSplitter.view.ThumbnailView": [],
  "PDFSplitter.view.Viewport": [],
  "Setu.Ajax": [],
  "Setu.Log": [],
  "Setu.Util": []
});
Ext.ClassManager.addNameAliasMappings({
  "PDFSplitter.Application": [],
  "PDFSplitter.controller.PdfSplitterController": [],
  "PDFSplitter.model.DocumentCategory": [],
  "PDFSplitter.model.DocumentType": [],
  "PDFSplitter.model.TreeModel": [],
  "PDFSplitter.store.DocumentCategory": [],
  "PDFSplitter.store.DocumentList": [],
  "PDFSplitter.store.DocumentType": [],
  "PDFSplitter.store.TreeStore": [],
  "PDFSplitter.ux.util.PDF.TextLayerBuilder": [],
  "PDFSplitter.view.DocumentCategory": [
    "widget.documentcategory"
  ],
  "PDFSplitter.view.DocumentList": [
    "widget.documentlist"
  ],
  "PDFSplitter.view.DocumentType": [
    "widget.documenttype"
  ],
  "PDFSplitter.view.ErrorPanel": [
    "widget.errorpanel"
  ],
  "PDFSplitter.view.Header": [
    "widget.pageheader"
  ],
  "PDFSplitter.view.MainPage": [
    "widget.mainpage"
  ],
  "PDFSplitter.view.PagingToolbar": [
    "widget.pagingtoolbar"
  ],
  "PDFSplitter.view.PdfPanel": [
    "widget.pdfpanel"
  ],
  "PDFSplitter.view.ReadFile": [
    "widget.readfile"
  ],
  "PDFSplitter.view.SearchBar": [
    "widget.searchbar"
  ],
  "PDFSplitter.view.SplitContainer": [
    "widget.splitcontainer"
  ],
  "PDFSplitter.view.SplitDetailsPanel": [
    "widget.splitdetailspanel"
  ],
  "PDFSplitter.view.TabView": [
    "widget.tabview"
  ],
  "PDFSplitter.view.TextContainer": [
    "widget.textcontainer"
  ],
  "PDFSplitter.view.ThumbnailView": [
    "widget.thumbnailview"
  ],
  "PDFSplitter.view.Viewport": [
    "widget.pdfviewport"
  ],
  "Setu.Ajax": [],
  "Setu.Log": [],
  "Setu.Util": []
});
