/*
 * File: app/view/category/TreeView.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AR.view.category.TreeView', {
    extend: 'Ext.dataview.NestedList',
    alias: 'widget.categoryTreeView',

    config: {
        detailCard: {
            xtype: 'articleDetail'
        },
        displayField: 'title',
        store: 'cattreestore',
        masked: {
            xtype: 'loadmask',
            message: 'Loading Catageories'
        },
        listeners: [
            {
                fn: 'onNestedlistLeafItemTap',
                event: 'leafitemtap'
            },
            {
                fn: 'onNestedlistBack',
                event: 'back'
            }
        ]
    },

    onNestedlistLeafItemTap: function(nestedlist, list, index, target, record, e, eOpts) {
         if(record.getData().content ==""){

        return false;
          }

             // console.log(record.getData().content);
                        var details=  Ext.ComponentQuery.query('articleDetail')[0] ;
             var saveBtn = Ext.getCmp('saveBtn');
        	saveBtn.setHidden(false);
        		details.setRecord(record);
                details.setHtml(record.getData().content);

    },

    onNestedlistBack: function(nestedlist, node, lastActiveList, detailCardActive, eOpts) {

        if(detailCardActive){

            Ext.getCmp('saveBtn').setHidden(true);
        }
    }

});