package com.wtc.samplems.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

//Imports ...

@Entity
@Table(name = "person")
public class Person {

// An autogenerated id (unique for each user in the db)
@Id
@GeneratedValue(strategy = GenerationType.AUTO)
private long id;

@NotNull
private String email;

@NotNull
private String name;

// Public methods

public Person() { }

public Person(long id) { 
 this.id = id;
}

public Person(String email, String name) {
 this.email = email;
 this.name = name;
}


//Getters and Setters
public long getId() {
	return id;
}

public void setId(long id) {
	this.id = id;
}

public String getEmail() {
	return email;
}

public void setEmail(String email) {
	this.email = email;
}

public String getName() {
	return name;
}

public void setName(String name) {
	this.name = name;
}


}