/*
 * File: app/view/Setting.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AR.view.Setting', {
    extend: 'Ext.form.Panel',
    alias: 'widget.settingsform',

    requires: [
        'AR.view.override.Setting',
        'Ext.form.FieldSet',
        'Ext.form.Select',
        'Ext.Label',
        'Ext.form.Toggle'
    ],

    config: {
        menubtn: 'false',
        itemId: 'myformpanel',
        items: [
            {
                xtype: 'fieldset',
                title: 'Application Settings',
                items: [
                    {
                        xtype: 'selectfield',
                        id: 'languagefield',
                        itemId: 'languagefield',
                        label: 'Launguage',
                        labelWidth: '50%',
                        displayField: 'langName',
                        valueField: 'langCode'
                    },
                    {
                        xtype: 'selectfield',
                        id: 'themefield',
                        label: 'Theme',
                        labelWidth: '50%',
                        displayField: 'themeName',
                        valueField: 'themeCode'
                    },
                    {
                        xtype: 'selectfield',
                        id: 'tabfield',
                        label: 'Default tab',
                        labelWidth: '50%',
                        displayField: 'tabName',
                        valueField: 'tabCode'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                title: 'Article Settings',
                items: [
                    {
                        xtype: 'label',
                        hidden: true,
                        html: 'Category View',
                        id: 'togglelabel'
                    },
                    {
                        xtype: 'togglefield',
                        contentEl: 'togglelabel',
                        id: 'togglecom',
                        itemId: 'mytogglefield',
                        label: 'Category View'
                    },
                    {
                        xtype: 'label',
                        hidden: true,
                        html: '10',
                        id: 'sliderval'
                    },
                    {
                        xtype: 'sliderfield',
                        contentEl: 'sliderval',
                        id: 'slidercom',
                        itemId: 'mysliderfield',
                        label: 'No Of Records Per Page',
                        value: [
                            10
                        ],
                        maxValue: 50
                    }
                ]
            },
            {
                xtype: 'button',
                itemId: 'settingssavebtn',
                margin: '0% 1% 0% 1%',
                text: 'Apply Settings'
            }
        ],
        listeners: [
            {
                fn: 'onMytogglefieldChange',
                event: 'change',
                delegate: '#togglecom'
            },
            {
                fn: 'onMysliderfieldChange',
                event: 'change',
                delegate: '#slidercom'
            }
        ]
    },

    onMytogglefieldChange: function(togglefield, newValue, oldValue, eOpts) {



        if(newValue===0){

        Ext.getCmp('togglelabel').setHtml(AR.locale.Labels.FIELD_ICON_VIEW_LABEL);

        }else{

        Ext.getCmp('togglelabel').setHtml(AR.locale.Labels.FIELD_LIST_VIEW_LABEL);

        }
    },

    onMysliderfieldChange: function(me, sl, thumb, newValue, oldValue, eOpts) {

        Ext.getCmp('sliderval').setHtml(newValue);
    }

});