/*
 * File: app/store/Author.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AR.store.Author', {
    extend: 'Ext.data.Store',

    requires: [
        'AR.model.Author',
        'Ext.data.proxy.JsonP',
        'Ext.data.reader.Json'
    ],

    config: {
        autoLoad: true,
        model: 'AR.model.Author',
        storeId: 'authorStore',
        proxy: {
            type: 'jsonp',
            api: {
                read: AR.util.Utility.api.allauthors
            },
            extraParams: {
                author_meta: 'email,posts'
            },
            reader: {
                type: 'json',
                rootProperty: 'authors'
            }
        }
    }
});