/*
 * File: app/view/article/Detail.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AR.view.article.Detail', {
    extend: 'Ext.Container',
    alias: 'widget.articleDetail',

    config: {
        saveopt: 'true',
        styleHtmlContent: true,
        scrollable: {
            direction: 'vertical'
        }
    }

});