/*
 * File: app/view/article/List.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AR.view.article.List', {
    extend: 'Ext.dataview.List',
    alias: 'widget.articlelist',

    requires: [
        'Ext.XTemplate',
        'AR.locale.Labels',
        'Ext.plugin.ListPaging'
    ],

    config: {
        masked: false,
        onItemDisclosure: true,
        itemTpl: Ext.create('Ext.XTemplate', 
            ' <div class="article-title"> {title}</div>',
            ' <div class="article-postedon"> ',
            '     <span class="postedon-text">{[this.labelval(\'POSTEDON_LABEL\')]} </span> {date:date("F j,Y")}</div>',
            ' <div class="article-by"> <span class="by-text">{[this.labelval(\'BY_LABEL\')]}</span> {author.first_name} {author.last_name}</div>',
            ' <div class="article-item-detail" style="clear:both;font-size:90%;"> {excerpt}</div>',
            {
                labelval: function(lab) {

                    return eval ("AR.locale.Labels."+lab);
                }
            }
        ),
        plugins: [
            {
                type: 'listpaging'
            }
        ]
    }

});