/*
 * File: app/controller/Article.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AR.controller.Article', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            articleList: 'articlelist',
            appnav: 'arnavigation'
        },

        control: {
            "articleList": {
                disclose: 'ShowArticleOndisclose'
            },
            "list": {
                itemtap: 'onListItemTap'
            }
        }
    },

    ShowArticleOndisclose: function(list, record, target, index, e, eOpts) {
        /*
        appNav=this.getAppnav();
        appNav.push({
        	xtype: 'articleDetail',
        	title: record.data.title,
        	record: record,
        	layout:'fit',
        	html: "<div class='articleContent'>"+record.data.content+"</div>"

        			});
        */

         var app = this.getApplication();

        if(app){

        		app.fireEvent('articleListItemDisclose',list, record, target, index, e, eOpts);

        }
    },

    onListItemTap: function(dataview, index, target, record, e, eOpts) {
         if(Ext.os.deviceType=="Phone"){

        var app = this.getApplication();

        if(app){

        		app.fireEvent('articleListItemDisclose',dataview, record, target, index, e, eOpts);

            }
           }
    },

    launch: function() {



        /* this.getArticleList();

         var articles=Ext.create('AR.store.ArticleStore',{autoLoad:true});
         this.getArticleList().setStore(articles);
        */
    }

});