/*
 * File: app/controller/Author.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AR.controller.Author', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            appnav: 'arnavigation',
            articleList: 'articlelist',
            authorview: 'authorIconView'
        },

        control: {
            "authorview": {
                itemtap: 'ShowArticleOfAuthor'
            }
        }
    },

    ShowArticleOfAuthor: function(dataview, index, target, record, e, eOpts) {

        /*
        Authortitle= record.getData().first_name;

        appNav=this.getAppnav();

        Articls_auth=Ext.create('AR.store.ArticleStore',{autoload:false});


        Articls_auth.setParams({'author':record.getData().id});
        Articls_auth.load();
        var Articles= Ext.create('AR.view.article.List',{store:Articls_auth,title:Authortitle,localArticleView : true});
        this.getAppnav().push(Articles);

        */

          this.getApplication().getController('Main').showArticlesOfAuthor(record.getData().id);
    }

});