/*
 * File: app/controller/Category.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('AR.controller.Category', {
    extend: 'Ext.app.Controller',

    config: {
        refs: {
            appnav: 'arnavigation',
            articleList: 'articlelist',
            categoryview: 'categoryIconView'
        },

        control: {
            "categoryview": {
                itemtap: 'ShowArticlesOfCategory'
            }
        }
    },

    ShowArticlesOfCategory: function(dataview, index, target, record, e, eOpts) {
        /*categoryId=record.data.id;
        categorytitle=record.data.title;
        appNav=this.getAppnav();

        Articls_cate=Ext.create('AR.store.ArticleStore',{autoload:false});




        Articls_cate.setParams({'cat':categoryId});
        Articls_cate.load();

        var Articles= Ext.create('AR.view.article.List',{store:Articls_cate,title:categorytitle,localArticleView : true});
        this.getAppnav().push(Articles); */

        this.getApplication().getController('Main').showArticlesOfCategory(record.getData().id);
    }

});